name: Update version

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    # https://stackoverflow.com/questions/70374602/getting-error-while-pushing-changes-to-my-own-public-repo-through-github-actions
    permissions:
      contents: write
      packages: write
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    
    - name: Add last git hash to index.html
      run: |
        git_hash=$(git --no-pager log -1 --oneline --format="%H")
        git_hash_8=${git_hash:0:8}
        python3 ./dev_tools.py --hash "$git_hash_8"

